version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis_celery
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: fastapi_app
    command: uvicorn fatorial:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build: .
    container_name: celery_worker
    command: celery -A celery_app.app worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
