version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_jogos
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn Teste:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A Teste.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis